-- ============================================================
-- FILE : 06_inventory_tables.sql
-- DESC : Inventory — GRNs, Stock Lots (FIFO), allocations,
--        bin location tracking
-- RUN  : After 05_procurement_tables.sql
-- ============================================================

USE MonitPaperDB;
GO

-- ------------------------------------------------------------
-- inventory.GRNs
-- Goods Receipt Note — created when material physically arrives.
-- One GRN per PO delivery (or partial delivery).
-- GRN is immutable after creation. Corrections = new GRN.
-- LotNumber is auto-generated by app:
--   {MillCode}-{CategoryCode}-{GSM}-{SizeLabel}-{YYYYMMDD}-{SEQ}
-- GRNNumber format: GRN-2024-0001
-- ------------------------------------------------------------
IF OBJECT_ID('inventory.GRNs', 'U') IS NULL
CREATE TABLE inventory.GRNs (
    Id                      INT             IDENTITY(1,1)   NOT NULL,
    GRNNumber               NVARCHAR(20)    NOT NULL,           -- GRN-2024-0001
    GRNDate                 DATE            NOT NULL,
    POId                    INT             NOT NULL,
    PONumber                NVARCHAR(20)    NOT NULL,           -- Denormalized for display
    PurchaseInvoiceNumber   NVARCHAR(50)    NULL,
    MillChallanNumber       NVARCHAR(50)    NULL,
    MillId                  INT             NOT NULL,
    MaterialId              INT             NOT NULL,
    GSM                     INT             NULL,
    SizeId                  INT             NULL,               -- → masters.PaperSizes
    OrderedQty              DECIMAL(18,4)   NOT NULL    DEFAULT 0,
    PreviouslyReceivedQty   DECIMAL(18,4)   NOT NULL    DEFAULT 0,
    ReceivedQty             DECIMAL(18,4)   NOT NULL,           -- This GRN
    ShortQty                DECIMAL(18,4)   NOT NULL    DEFAULT 0,
    DamagedQty              DECIMAL(18,4)   NOT NULL    DEFAULT 0,
    BalanceQty              DECIMAL(18,4)   NOT NULL    DEFAULT 0,
    ReceivedWeightMT        DECIMAL(10,4)   NULL,
    ExpectedWeightMT        DECIMAL(10,4)   NULL,
    WarehouseId             INT             NULL,
    BinLocationId           INT             NULL,               -- → masters.WarehouseBins
    SuggestedBin            NVARCHAR(20)    NULL,
    Condition               NVARCHAR(30)    NULL,
    -- Good / Slight Damage / Wet / Torn / Mixed GSM
    QCResult                NVARCHAR(50)    NULL,
    -- Accepted / Accepted with Remark / Rejected / Hold
    QualityGrade            NVARCHAR(20)    NULL,               -- A Grade / B Grade / Rejected
    LotNumber               NVARCHAR(100)   NOT NULL,           -- Auto-generated (see desc above)
    LRNumber                NVARCHAR(50)    NULL,
    TransporterId           INT             NULL,
    VehicleNumber           NVARCHAR(20)    NULL,
    DriverName              NVARCHAR(200)   NULL,
    FreightAmount           DECIMAL(18,4)   NOT NULL    DEFAULT 0,
    UnloadingCharges        DECIMAL(18,4)   NOT NULL    DEFAULT 0,
    InvoiceEligible         BIT             NOT NULL    DEFAULT 1,
    Remarks                 NVARCHAR(1000)  NULL,

    CreatedAt   DATETIME2       NOT NULL    DEFAULT GETUTCDATE(),
    CreatedBy   NVARCHAR(100)   NOT NULL,
    UpdatedAt   DATETIME2       NULL,
    UpdatedBy   NVARCHAR(100)   NULL,
    IsDeleted   BIT             NOT NULL    DEFAULT 0,
    DeletedAt   DATETIME2       NULL,
    DeletedBy   NVARCHAR(100)   NULL,

    CONSTRAINT PK_GRNs                  PRIMARY KEY (Id),
    CONSTRAINT UQ_GRNs_Number           UNIQUE (GRNNumber),
    CONSTRAINT UQ_GRNs_LotNumber        UNIQUE (LotNumber),
    CONSTRAINT FK_GRNs_PO               FOREIGN KEY (POId)
                                        REFERENCES procurement.PurchaseOrders(Id),
    CONSTRAINT FK_GRNs_Mill             FOREIGN KEY (MillId)
                                        REFERENCES masters.Mills(Id),
    CONSTRAINT FK_GRNs_Material         FOREIGN KEY (MaterialId)
                                        REFERENCES masters.Materials(Id),
    CONSTRAINT FK_GRNs_Size             FOREIGN KEY (SizeId)
                                        REFERENCES masters.PaperSizes(Id),
    CONSTRAINT FK_GRNs_Warehouse        FOREIGN KEY (WarehouseId)
                                        REFERENCES masters.Warehouses(Id),
    CONSTRAINT FK_GRNs_Bin             FOREIGN KEY (BinLocationId)
                                        REFERENCES masters.WarehouseBins(Id),
    CONSTRAINT FK_GRNs_Transporter      FOREIGN KEY (TransporterId)
                                        REFERENCES masters.Transporters(Id)
);
GO

-- ------------------------------------------------------------
-- inventory.StockLots
-- One lot = one GRN receipt. FIFO picking is based on GRNDate.
-- AvailableQty is a computed, persisted column for fast queries.
-- FIFOSequence is assigned by app at GRN time (auto-increment
-- per MaterialId) so FIFO order never needs re-sorting.
-- ------------------------------------------------------------
IF OBJECT_ID('inventory.StockLots', 'U') IS NULL
CREATE TABLE inventory.StockLots (
    Id              INT             IDENTITY(1,1)   NOT NULL,
    LotNumber       NVARCHAR(100)   NOT NULL,           -- Same as GRN.LotNumber
    GRNId           INT             NOT NULL,
    MaterialId      INT             NOT NULL,
    MillId          INT             NOT NULL,
    GSM             INT             NULL,
    SizeId          INT             NULL,
    WarehouseId     INT             NULL,
    BinLocationId   INT             NULL,
    GRNDate         DATE            NOT NULL,           -- FIFO sort key
    OpeningQty      DECIMAL(18,4)   NOT NULL,
    CurrentQty      DECIMAL(18,4)   NOT NULL,
    ReservedQty     DECIMAL(18,4)   NOT NULL    DEFAULT 0,
    AvailableQty    AS (CurrentQty - ReservedQty) PERSISTED,
    CostPerUnit     DECIMAL(18,4)   NULL,
    TotalCost       DECIMAL(18,4)   NULL,
    Condition       NVARCHAR(30)    NULL,
    QualityGrade    NVARCHAR(20)    NULL,
    [Status]        NVARCHAR(30)    NOT NULL    DEFAULT 'Available',
    -- Available → Partially Allocated → Fully Allocated → Exhausted → Blocked
    FIFOSequence    INT             NOT NULL,           -- Lower = picked first within MaterialId

    CreatedAt   DATETIME2       NOT NULL    DEFAULT GETUTCDATE(),
    CreatedBy   NVARCHAR(100)   NOT NULL,
    UpdatedAt   DATETIME2       NULL,
    UpdatedBy   NVARCHAR(100)   NULL,
    IsDeleted   BIT             NOT NULL    DEFAULT 0,
    DeletedAt   DATETIME2       NULL,
    DeletedBy   NVARCHAR(100)   NULL,

    CONSTRAINT PK_StockLots             PRIMARY KEY (Id),
    CONSTRAINT UQ_StockLots_LotNumber   UNIQUE (LotNumber),
    CONSTRAINT FK_StockLots_GRN         FOREIGN KEY (GRNId)
                                        REFERENCES inventory.GRNs(Id),
    CONSTRAINT FK_StockLots_Material    FOREIGN KEY (MaterialId)
                                        REFERENCES masters.Materials(Id),
    CONSTRAINT FK_StockLots_Mill        FOREIGN KEY (MillId)
                                        REFERENCES masters.Mills(Id),
    CONSTRAINT FK_StockLots_Size        FOREIGN KEY (SizeId)
                                        REFERENCES masters.PaperSizes(Id),
    CONSTRAINT FK_StockLots_Warehouse   FOREIGN KEY (WarehouseId)
                                        REFERENCES masters.Warehouses(Id),
    CONSTRAINT FK_StockLots_Bin         FOREIGN KEY (BinLocationId)
                                        REFERENCES masters.WarehouseBins(Id)
);
GO

-- ------------------------------------------------------------
-- inventory.StockAllocations
-- Links a stock lot to a Sales Order line.
-- When material is physically dispatched, status → Dispatched.
-- Only system/service updates this — never direct API.
-- ------------------------------------------------------------
IF OBJECT_ID('inventory.StockAllocations', 'U') IS NULL
CREATE TABLE inventory.StockAllocations (
    Id              INT             IDENTITY(1,1)   NOT NULL,
    StockLotId      INT             NOT NULL,
    SOLineId        INT             NOT NULL,
    SOId            INT             NOT NULL,           -- Denormalized for fast SO-level queries
    AllocatedQty    DECIMAL(18,4)   NOT NULL,
    AllocationType  NVARCHAR(30)    NULL,               -- Manual / Auto-FIFO
    [Status]        NVARCHAR(30)    NOT NULL    DEFAULT 'Pending',
    -- Pending → Confirmed → Dispatched → Cancelled

    CreatedAt   DATETIME2       NOT NULL    DEFAULT GETUTCDATE(),
    CreatedBy   NVARCHAR(100)   NOT NULL,
    UpdatedAt   DATETIME2       NULL,
    UpdatedBy   NVARCHAR(100)   NULL,
    IsDeleted   BIT             NOT NULL    DEFAULT 0,
    DeletedAt   DATETIME2       NULL,
    DeletedBy   NVARCHAR(100)   NULL,

    CONSTRAINT PK_StockAllocations              PRIMARY KEY (Id),
    CONSTRAINT FK_StockAllocations_StockLot     FOREIGN KEY (StockLotId)
                                                REFERENCES inventory.StockLots(Id),
    CONSTRAINT FK_StockAllocations_SOLine       FOREIGN KEY (SOLineId)
                                                REFERENCES sales.SalesOrderLines(Id),
    CONSTRAINT FK_StockAllocations_SO           FOREIGN KEY (SOId)
                                                REFERENCES sales.SalesOrders(Id)
);
GO

-- ------------------------------------------------------------
-- inventory.PurchaseAllocations
-- Links a PO item to a Sales Order line (in-transit coverage).
-- Used by the coverage engine to show "this PO is covering
-- this SO line, even though material hasn't arrived yet".
-- ------------------------------------------------------------
IF OBJECT_ID('inventory.PurchaseAllocations', 'U') IS NULL
CREATE TABLE inventory.PurchaseAllocations (
    Id              INT             IDENTITY(1,1)   NOT NULL,
    POItemId        INT             NOT NULL,
    SOLineId        INT             NOT NULL,
    AllocatedQty    DECIMAL(18,4)   NOT NULL,
    [Status]        NVARCHAR(30)    NOT NULL    DEFAULT 'Pending',
    -- Pending → Received (converted to StockAllocation on GRN) → Cancelled

    CreatedAt   DATETIME2       NOT NULL    DEFAULT GETUTCDATE(),
    CreatedBy   NVARCHAR(100)   NOT NULL,
    UpdatedAt   DATETIME2       NULL,
    UpdatedBy   NVARCHAR(100)   NULL,
    IsDeleted   BIT             NOT NULL    DEFAULT 0,
    DeletedAt   DATETIME2       NULL,
    DeletedBy   NVARCHAR(100)   NULL,

    CONSTRAINT PK_PurchaseAllocations           PRIMARY KEY (Id),
    CONSTRAINT FK_PurchaseAllocations_POItem    FOREIGN KEY (POItemId)
                                                REFERENCES procurement.PurchaseOrderItems(Id),
    CONSTRAINT FK_PurchaseAllocations_SOLine    FOREIGN KEY (SOLineId)
                                                REFERENCES sales.SalesOrderLines(Id)
);
GO

-- ------------------------------------------------------------
-- inventory.BinLocations
-- Tracks current fill state of each bin.
-- CurrentCapacity is updated by app when stock moves in/out.
-- This is different from masters.WarehouseBins which holds
-- the static definition of the bin.
-- ------------------------------------------------------------
IF OBJECT_ID('inventory.BinLocations', 'U') IS NULL
CREATE TABLE inventory.BinLocations (
    Id              INT             IDENTITY(1,1)   NOT NULL,
    WarehouseId     INT             NOT NULL,
    BinId           INT             NOT NULL,           -- → masters.WarehouseBins
    BinCode         NVARCHAR(20)    NOT NULL,           -- Denormalized
    CurrentCapacity INT             NOT NULL    DEFAULT 0,
    MaxCapacity     INT             NOT NULL    DEFAULT 0,
    [Status]        NVARCHAR(20)    NOT NULL    DEFAULT 'Empty',
    -- Empty → Partial → Full
    LastActivity    DATETIME2       NULL,

    CreatedAt   DATETIME2       NOT NULL    DEFAULT GETUTCDATE(),
    CreatedBy   NVARCHAR(100)   NOT NULL,
    UpdatedAt   DATETIME2       NULL,
    UpdatedBy   NVARCHAR(100)   NULL,
    IsDeleted   BIT             NOT NULL    DEFAULT 0,
    DeletedAt   DATETIME2       NULL,
    DeletedBy   NVARCHAR(100)   NULL,

    CONSTRAINT PK_BinLocations          PRIMARY KEY (Id),
    CONSTRAINT UQ_BinLocations          UNIQUE (WarehouseId, BinId),
    CONSTRAINT FK_BinLocations_WH       FOREIGN KEY (WarehouseId)
                                        REFERENCES masters.Warehouses(Id),
    CONSTRAINT FK_BinLocations_Bin      FOREIGN KEY (BinId)
                                        REFERENCES masters.WarehouseBins(Id)
);
GO

PRINT '✓ inventory tables created.';
GO
