-- ============================================================
-- FILE : 07_logistics_tables.sql
-- DESC : Logistics flow — Pick Plans → Truck Load Plans →
--        Challans → In-Transit Tracking
-- RUN  : After 06_inventory_tables.sql
-- ============================================================

USE MonitPaperDB;
GO

-- ------------------------------------------------------------
-- logistics.PickPlans
-- Warehouse picking instruction for a Sales Order.
-- Lines are auto-generated by FIFO logic from stock lots.
-- PlanNumber format: PP-2024-0001
-- ------------------------------------------------------------
IF OBJECT_ID('logistics.PickPlans', 'U') IS NULL
CREATE TABLE logistics.PickPlans (
    Id          INT             IDENTITY(1,1)   NOT NULL,
    PlanNumber  NVARCHAR(20)    NOT NULL,           -- PP-2024-0001
    PlanDate    DATE            NOT NULL,
    SOId        INT             NOT NULL,
    [Status]    NVARCHAR(20)    NOT NULL    DEFAULT 'Draft',
    -- Draft → Confirmed → In Progress → Picked → Cancelled
    TotalLines  INT             NOT NULL    DEFAULT 0,
    Remarks     NVARCHAR(500)   NULL,

    CreatedAt   DATETIME2       NOT NULL    DEFAULT GETUTCDATE(),
    CreatedBy   NVARCHAR(100)   NOT NULL,
    UpdatedAt   DATETIME2       NULL,
    UpdatedBy   NVARCHAR(100)   NULL,
    IsDeleted   BIT             NOT NULL    DEFAULT 0,
    DeletedAt   DATETIME2       NULL,
    DeletedBy   NVARCHAR(100)   NULL,

    CONSTRAINT PK_PickPlans             PRIMARY KEY (Id),
    CONSTRAINT UQ_PickPlans_Number      UNIQUE (PlanNumber),
    CONSTRAINT FK_PickPlans_SO          FOREIGN KEY (SOId)
                                        REFERENCES sales.SalesOrders(Id)
);
GO

-- ------------------------------------------------------------
-- logistics.PickPlanLines
-- One line = pick X qty from a specific stock lot in a bin.
-- FIFOSequence mirrors StockLots.FIFOSequence for ordering.
-- ------------------------------------------------------------
IF OBJECT_ID('logistics.PickPlanLines', 'U') IS NULL
CREATE TABLE logistics.PickPlanLines (
    Id              INT             IDENTITY(1,1)   NOT NULL,
    PickPlanId      INT             NOT NULL,
    LineNumber      INT             NOT NULL,
    StockLotId      INT             NOT NULL,
    BinLocationId   INT             NULL,           -- → masters.WarehouseBins
    MaterialId      INT             NULL,           -- Denormalized for display
    SOLineId        INT             NULL,           -- → sales.SalesOrderLines
    PickQty         DECIMAL(18,4)   NOT NULL,
    PickedQty       DECIMAL(18,4)   NOT NULL    DEFAULT 0,
    FIFOSequence    INT             NULL,
    [Status]        NVARCHAR(30)    NOT NULL    DEFAULT 'Pending',
    -- Pending → Picked → Short Picked → Cancelled

    CreatedAt   DATETIME2       NOT NULL    DEFAULT GETUTCDATE(),
    CreatedBy   NVARCHAR(100)   NOT NULL,
    UpdatedAt   DATETIME2       NULL,
    UpdatedBy   NVARCHAR(100)   NULL,
    IsDeleted   BIT             NOT NULL    DEFAULT 0,
    DeletedAt   DATETIME2       NULL,
    DeletedBy   NVARCHAR(100)   NULL,

    CONSTRAINT PK_PickPlanLines             PRIMARY KEY (Id),
    CONSTRAINT UQ_PickPlanLines             UNIQUE (PickPlanId, LineNumber),
    CONSTRAINT FK_PickPlanLines_Plan        FOREIGN KEY (PickPlanId)
                                            REFERENCES logistics.PickPlans(Id),
    CONSTRAINT FK_PickPlanLines_StockLot    FOREIGN KEY (StockLotId)
                                            REFERENCES inventory.StockLots(Id),
    CONSTRAINT FK_PickPlanLines_Bin         FOREIGN KEY (BinLocationId)
                                            REFERENCES masters.WarehouseBins(Id),
    CONSTRAINT FK_PickPlanLines_Material    FOREIGN KEY (MaterialId)
                                            REFERENCES masters.Materials(Id),
    CONSTRAINT FK_PickPlanLines_SOLine      FOREIGN KEY (SOLineId)
                                            REFERENCES sales.SalesOrderLines(Id)
);
GO

-- ------------------------------------------------------------
-- logistics.TruckLoadPlans
-- A plan for loading one truck. Can carry items from multiple
-- POs (mill direct) or from stock (godown dispatch).
-- PlanNumber format: TLP-2024-0001
-- ------------------------------------------------------------
IF OBJECT_ID('logistics.TruckLoadPlans', 'U') IS NULL
CREATE TABLE logistics.TruckLoadPlans (
    Id                  INT             IDENTITY(1,1)   NOT NULL,
    PlanNumber          NVARCHAR(20)    NOT NULL,           -- TLP-2024-0001
    PlanDate            DATE            NOT NULL,
    VehicleId           INT             NULL,               -- → masters.TransporterVehicles
    TruckNumber         NVARCHAR(20)    NULL,
    DriverName          NVARCHAR(200)   NULL,
    DriverPhone         NVARCHAR(20)    NULL,
    TransporterId       INT             NULL,
    TruckCapacityKg     DECIMAL(10,2)   NULL,
    Origin              NVARCHAR(200)   NULL,               -- Mill name OR Godown name
    DeliveryMode        NVARCHAR(30)    NULL,
    -- Direct To Customer / To Godown / Multi-Stop
    PlannedLoadDate     DATE            NULL,
    PlannedDeliveryDate DATE            NULL,
    ActualLoadDate      DATE            NULL,
    ActualDeliveryDate  DATE            NULL,
    [Status]            NVARCHAR(20)    NOT NULL    DEFAULT 'Planned',
    -- Planned → Loading → In Transit → Delivered
    InTransitTrackerId  INT             NULL,               -- Set when dispatched

    CreatedAt   DATETIME2       NOT NULL    DEFAULT GETUTCDATE(),
    CreatedBy   NVARCHAR(100)   NOT NULL,
    UpdatedAt   DATETIME2       NULL,
    UpdatedBy   NVARCHAR(100)   NULL,
    IsDeleted   BIT             NOT NULL    DEFAULT 0,
    DeletedAt   DATETIME2       NULL,
    DeletedBy   NVARCHAR(100)   NULL,

    CONSTRAINT PK_TruckLoadPlans            PRIMARY KEY (Id),
    CONSTRAINT UQ_TruckLoadPlans_Number     UNIQUE (PlanNumber),
    CONSTRAINT FK_TruckLoadPlans_Vehicle    FOREIGN KEY (VehicleId)
                                            REFERENCES masters.TransporterVehicles(Id),
    CONSTRAINT FK_TruckLoadPlans_Transp     FOREIGN KEY (TransporterId)
                                            REFERENCES masters.Transporters(Id)
    -- FK to InTransitTrackings added after that table is created
);
GO

-- ------------------------------------------------------------
-- logistics.TruckLoadPlanItems
-- Each line = one material batch loaded on this truck.
-- Can reference a PO item (mill direct) or a stock lot (godown).
-- ------------------------------------------------------------
IF OBJECT_ID('logistics.TruckLoadPlanItems', 'U') IS NULL
CREATE TABLE logistics.TruckLoadPlanItems (
    Id              INT             IDENTITY(1,1)   NOT NULL,
    TLPId           INT             NOT NULL,
    LineNumber      INT             NOT NULL,
    POId            INT             NULL,           -- Mill direct delivery
    POItemId        INT             NULL,
    MaterialId      INT             NULL,
    GSM             INT             NULL,
    Size            NVARCHAR(50)    NULL,
    Quantity        DECIMAL(18,4)   NULL,
    WeightKg        DECIMAL(10,2)   NULL,
    PickPlanLineId  INT             NULL,           -- Godown dispatch
    StockLotId      INT             NULL,
    CustomerId      INT             NULL,
    DeliveryAddress NVARCHAR(500)   NULL,

    CreatedAt   DATETIME2       NOT NULL    DEFAULT GETUTCDATE(),
    CreatedBy   NVARCHAR(100)   NOT NULL,
    UpdatedAt   DATETIME2       NULL,
    UpdatedBy   NVARCHAR(100)   NULL,
    IsDeleted   BIT             NOT NULL    DEFAULT 0,
    DeletedAt   DATETIME2       NULL,
    DeletedBy   NVARCHAR(100)   NULL,

    CONSTRAINT PK_TruckLoadPlanItems            PRIMARY KEY (Id),
    CONSTRAINT UQ_TruckLoadPlanItems            UNIQUE (TLPId, LineNumber),
    CONSTRAINT FK_TruckLoadPlanItems_TLP        FOREIGN KEY (TLPId)
                                                REFERENCES logistics.TruckLoadPlans(Id),
    CONSTRAINT FK_TruckLoadPlanItems_PO         FOREIGN KEY (POId)
                                                REFERENCES procurement.PurchaseOrders(Id),
    CONSTRAINT FK_TruckLoadPlanItems_POItem     FOREIGN KEY (POItemId)
                                                REFERENCES procurement.PurchaseOrderItems(Id),
    CONSTRAINT FK_TruckLoadPlanItems_Material   FOREIGN KEY (MaterialId)
                                                REFERENCES masters.Materials(Id),
    CONSTRAINT FK_TruckLoadPlanItems_PickLine   FOREIGN KEY (PickPlanLineId)
                                                REFERENCES logistics.PickPlanLines(Id),
    CONSTRAINT FK_TruckLoadPlanItems_StockLot   FOREIGN KEY (StockLotId)
                                                REFERENCES inventory.StockLots(Id),
    CONSTRAINT FK_TruckLoadPlanItems_Customer   FOREIGN KEY (CustomerId)
                                                REFERENCES masters.Customers(Id)
);
GO

-- ------------------------------------------------------------
-- logistics.InTransitTrackings
-- Live tracking record created when a truck departs.
-- TRK-2024-0001 format.
-- DelayHours is updated by app when driver check-ins are late.
-- ------------------------------------------------------------
IF OBJECT_ID('logistics.InTransitTrackings', 'U') IS NULL
CREATE TABLE logistics.InTransitTrackings (
    Id                  INT             IDENTITY(1,1)   NOT NULL,
    TrackingNumber      NVARCHAR(20)    NOT NULL,           -- TRK-2024-0001
    TLPId               INT             NULL,
    TransporterId       INT             NULL,
    VehicleNumber       NVARCHAR(20)    NULL,
    DriverName          NVARCHAR(200)   NULL,
    DriverPhone         NVARCHAR(20)    NULL,
    Origin              NVARCHAR(200)   NULL,
    Destination         NVARCHAR(200)   NULL,
    DispatchDateTime    DATETIME2       NULL,
    ExpectedArrival     DATETIME2       NULL,
    ActualArrival       DATETIME2       NULL,
    CurrentStatus       NVARCHAR(30)    NOT NULL    DEFAULT 'Dispatched',
    -- Dispatched → On Route → Reached → Delivered → Delayed
    CurrentLocation     NVARCHAR(200)   NULL,
    LastLocationUpdate  DATETIME2       NULL,
    LRNumber            NVARCHAR(50)    NULL,
    TotalQuantity       DECIMAL(18,4)   NULL,
    TotalWeightKg       DECIMAL(10,2)   NULL,
    DelayHours          INT             NOT NULL    DEFAULT 0,
    DelayReason         NVARCHAR(500)   NULL,
    Remarks             NVARCHAR(1000)  NULL,

    CreatedAt   DATETIME2       NOT NULL    DEFAULT GETUTCDATE(),
    CreatedBy   NVARCHAR(100)   NOT NULL,
    UpdatedAt   DATETIME2       NULL,
    UpdatedBy   NVARCHAR(100)   NULL,
    IsDeleted   BIT             NOT NULL    DEFAULT 0,
    DeletedAt   DATETIME2       NULL,
    DeletedBy   NVARCHAR(100)   NULL,

    CONSTRAINT PK_InTransitTrackings            PRIMARY KEY (Id),
    CONSTRAINT UQ_InTransitTrackings_Number     UNIQUE (TrackingNumber),
    CONSTRAINT FK_InTransitTrackings_TLP        FOREIGN KEY (TLPId)
                                                REFERENCES logistics.TruckLoadPlans(Id),
    CONSTRAINT FK_InTransitTrackings_Transp     FOREIGN KEY (TransporterId)
                                                REFERENCES masters.Transporters(Id)
);
GO

-- Now add the FK from TruckLoadPlans → InTransitTrackings
ALTER TABLE logistics.TruckLoadPlans
    ADD CONSTRAINT FK_TruckLoadPlans_InTransit
    FOREIGN KEY (InTransitTrackerId)
    REFERENCES logistics.InTransitTrackings(Id);
GO

-- ------------------------------------------------------------
-- logistics.Challans
-- Delivery document issued for each customer delivery.
-- Created from a TLP or directly from a SO.
-- ChallanNumber format: CHN-2024-0001
-- ------------------------------------------------------------
IF OBJECT_ID('logistics.Challans', 'U') IS NULL
CREATE TABLE logistics.Challans (
    Id                  INT             IDENTITY(1,1)   NOT NULL,
    ChallanNumber       NVARCHAR(20)    NOT NULL,           -- CHN-2024-0001
    ChallanDate         DATE            NOT NULL,
    TLPId               INT             NULL,
    SOId                INT             NULL,
    CustomerId          INT             NOT NULL,
    DeliveryAddressId   INT             NULL,               -- → masters.CustomerDeliveryLocations
    TransporterId       INT             NULL,
    VehicleNumber       NVARCHAR(20)    NULL,
    DriverName          NVARCHAR(200)   NULL,
    DriverPhone         NVARCHAR(20)    NULL,
    LRNumber            NVARCHAR(50)    NULL,
    TotalQuantity       DECIMAL(18,4)   NOT NULL    DEFAULT 0,
    TotalWeightKg       DECIMAL(10,2)   NULL,
    TotalValue          DECIMAL(18,4)   NOT NULL    DEFAULT 0,
    [Status]            NVARCHAR(20)    NOT NULL    DEFAULT 'Draft',
    -- Draft → Issued → Delivered → Cancelled
    EWayBillNumber      NVARCHAR(50)    NULL,
    Remarks             NVARCHAR(1000)  NULL,

    CreatedAt   DATETIME2       NOT NULL    DEFAULT GETUTCDATE(),
    CreatedBy   NVARCHAR(100)   NOT NULL,
    UpdatedAt   DATETIME2       NULL,
    UpdatedBy   NVARCHAR(100)   NULL,
    IsDeleted   BIT             NOT NULL    DEFAULT 0,
    DeletedAt   DATETIME2       NULL,
    DeletedBy   NVARCHAR(100)   NULL,

    CONSTRAINT PK_Challans              PRIMARY KEY (Id),
    CONSTRAINT UQ_Challans_Number       UNIQUE (ChallanNumber),
    CONSTRAINT FK_Challans_TLP          FOREIGN KEY (TLPId)
                                        REFERENCES logistics.TruckLoadPlans(Id),
    CONSTRAINT FK_Challans_SO           FOREIGN KEY (SOId)
                                        REFERENCES sales.SalesOrders(Id),
    CONSTRAINT FK_Challans_Customer     FOREIGN KEY (CustomerId)
                                        REFERENCES masters.Customers(Id),
    CONSTRAINT FK_Challans_Address      FOREIGN KEY (DeliveryAddressId)
                                        REFERENCES masters.CustomerDeliveryLocations(Id),
    CONSTRAINT FK_Challans_Transporter  FOREIGN KEY (TransporterId)
                                        REFERENCES masters.Transporters(Id)
);
GO

-- ------------------------------------------------------------
-- logistics.ChallanLines
-- Line items of a challan. Each line = one material.
-- ------------------------------------------------------------
IF OBJECT_ID('logistics.ChallanLines', 'U') IS NULL
CREATE TABLE logistics.ChallanLines (
    Id          INT             IDENTITY(1,1)   NOT NULL,
    ChallanId   INT             NOT NULL,
    LineNumber  INT             NOT NULL,
    MaterialId  INT             NULL,
    GSM         INT             NULL,
    Size        NVARCHAR(50)    NULL,
    Quantity    DECIMAL(18,4)   NOT NULL,
    WeightKg    DECIMAL(10,2)   NULL,
    Rate        DECIMAL(18,4)   NULL,
    Amount      DECIMAL(18,4)   NULL,
    StockLotId  INT             NULL,

    CreatedAt   DATETIME2       NOT NULL    DEFAULT GETUTCDATE(),
    CreatedBy   NVARCHAR(100)   NOT NULL,
    UpdatedAt   DATETIME2       NULL,
    UpdatedBy   NVARCHAR(100)   NULL,
    IsDeleted   BIT             NOT NULL    DEFAULT 0,
    DeletedAt   DATETIME2       NULL,
    DeletedBy   NVARCHAR(100)   NULL,

    CONSTRAINT PK_ChallanLines              PRIMARY KEY (Id),
    CONSTRAINT UQ_ChallanLines              UNIQUE (ChallanId, LineNumber),
    CONSTRAINT FK_ChallanLines_Challan      FOREIGN KEY (ChallanId)
                                            REFERENCES logistics.Challans(Id),
    CONSTRAINT FK_ChallanLines_Material     FOREIGN KEY (MaterialId)
                                            REFERENCES masters.Materials(Id),
    CONSTRAINT FK_ChallanLines_StockLot     FOREIGN KEY (StockLotId)
                                            REFERENCES inventory.StockLots(Id)
);
GO

PRINT '✓ logistics tables created.';
GO
